/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Color, } from "./interface";
export namespace Components {
    interface SenButton {
        /**
          * Button type
         */
        "buttonType": "button" | "submit" | "reset";
        /**
          * Button variant
         */
        "color"?: Color;
        /**
          * Disables the button
         */
        "disabled": boolean;
    }
    interface SenCol {
        /**
          * Large column width
         */
        "lg"?: number;
        /**
          * Medium column width
         */
        "md"?: number;
        /**
          * Small column width
         */
        "sm"?: number;
        /**
          * X-Large column width
         */
        "xl"?: number;
        /**
          * X-small column width
         */
        "xs"?: number;
    }
    interface SenContainer {
    }
    interface SenRow {
    }
}
declare global {
    interface HTMLSenButtonElement extends Components.SenButton, HTMLStencilElement {
    }
    var HTMLSenButtonElement: {
        prototype: HTMLSenButtonElement;
        new (): HTMLSenButtonElement;
    };
    interface HTMLSenColElement extends Components.SenCol, HTMLStencilElement {
    }
    var HTMLSenColElement: {
        prototype: HTMLSenColElement;
        new (): HTMLSenColElement;
    };
    interface HTMLSenContainerElement extends Components.SenContainer, HTMLStencilElement {
    }
    var HTMLSenContainerElement: {
        prototype: HTMLSenContainerElement;
        new (): HTMLSenContainerElement;
    };
    interface HTMLSenRowElement extends Components.SenRow, HTMLStencilElement {
    }
    var HTMLSenRowElement: {
        prototype: HTMLSenRowElement;
        new (): HTMLSenRowElement;
    };
    interface HTMLElementTagNameMap {
        "sen-button": HTMLSenButtonElement;
        "sen-col": HTMLSenColElement;
        "sen-container": HTMLSenContainerElement;
        "sen-row": HTMLSenRowElement;
    }
}
declare namespace LocalJSX {
    interface SenButton {
        /**
          * Button type
         */
        "buttonType"?: "button" | "submit" | "reset";
        /**
          * Button variant
         */
        "color"?: Color;
        /**
          * Disables the button
         */
        "disabled"?: boolean;
    }
    interface SenCol {
        /**
          * Large column width
         */
        "lg"?: number;
        /**
          * Medium column width
         */
        "md"?: number;
        /**
          * Small column width
         */
        "sm"?: number;
        /**
          * X-Large column width
         */
        "xl"?: number;
        /**
          * X-small column width
         */
        "xs"?: number;
    }
    interface SenContainer {
    }
    interface SenRow {
    }
    interface IntrinsicElements {
        "sen-button": SenButton;
        "sen-col": SenCol;
        "sen-container": SenContainer;
        "sen-row": SenRow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sen-button": LocalJSX.SenButton & JSXBase.HTMLAttributes<HTMLSenButtonElement>;
            "sen-col": LocalJSX.SenCol & JSXBase.HTMLAttributes<HTMLSenColElement>;
            "sen-container": LocalJSX.SenContainer & JSXBase.HTMLAttributes<HTMLSenContainerElement>;
            "sen-row": LocalJSX.SenRow & JSXBase.HTMLAttributes<HTMLSenRowElement>;
        }
    }
}
