/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Color, } from "./interface";
export namespace Components {
    interface SenApp {
    }
    interface SenButton {
        /**
          * Button type
         */
        "buttonType": "button" | "submit" | "reset";
        /**
          * Button variant
         */
        "color"?: Color;
        /**
          * Disables the button
         */
        "disabled": boolean;
    }
    interface SenButtonGroup {
    }
    interface SenCol {
        /**
          * Large column width
         */
        "lg"?: string | number;
        /**
          * Medium column width
         */
        "md"?: string | number;
        /**
          * Small column width
         */
        "sm"?: string | number;
        /**
          * X-Large column width
         */
        "xl"?: string | number;
        /**
          * X-small column width
         */
        "xs"?: string | number;
    }
    interface SenContainer {
    }
    interface SenFormField {
        /**
          * Label of the form field
         */
        "label": string;
    }
    interface SenRow {
    }
}
declare global {
    interface HTMLSenAppElement extends Components.SenApp, HTMLStencilElement {
    }
    var HTMLSenAppElement: {
        prototype: HTMLSenAppElement;
        new (): HTMLSenAppElement;
    };
    interface HTMLSenButtonElement extends Components.SenButton, HTMLStencilElement {
    }
    var HTMLSenButtonElement: {
        prototype: HTMLSenButtonElement;
        new (): HTMLSenButtonElement;
    };
    interface HTMLSenButtonGroupElement extends Components.SenButtonGroup, HTMLStencilElement {
    }
    var HTMLSenButtonGroupElement: {
        prototype: HTMLSenButtonGroupElement;
        new (): HTMLSenButtonGroupElement;
    };
    interface HTMLSenColElement extends Components.SenCol, HTMLStencilElement {
    }
    var HTMLSenColElement: {
        prototype: HTMLSenColElement;
        new (): HTMLSenColElement;
    };
    interface HTMLSenContainerElement extends Components.SenContainer, HTMLStencilElement {
    }
    var HTMLSenContainerElement: {
        prototype: HTMLSenContainerElement;
        new (): HTMLSenContainerElement;
    };
    interface HTMLSenFormFieldElement extends Components.SenFormField, HTMLStencilElement {
    }
    var HTMLSenFormFieldElement: {
        prototype: HTMLSenFormFieldElement;
        new (): HTMLSenFormFieldElement;
    };
    interface HTMLSenRowElement extends Components.SenRow, HTMLStencilElement {
    }
    var HTMLSenRowElement: {
        prototype: HTMLSenRowElement;
        new (): HTMLSenRowElement;
    };
    interface HTMLElementTagNameMap {
        "sen-app": HTMLSenAppElement;
        "sen-button": HTMLSenButtonElement;
        "sen-button-group": HTMLSenButtonGroupElement;
        "sen-col": HTMLSenColElement;
        "sen-container": HTMLSenContainerElement;
        "sen-form-field": HTMLSenFormFieldElement;
        "sen-row": HTMLSenRowElement;
    }
}
declare namespace LocalJSX {
    interface SenApp {
    }
    interface SenButton {
        /**
          * Button type
         */
        "buttonType"?: "button" | "submit" | "reset";
        /**
          * Button variant
         */
        "color"?: Color;
        /**
          * Disables the button
         */
        "disabled"?: boolean;
    }
    interface SenButtonGroup {
    }
    interface SenCol {
        /**
          * Large column width
         */
        "lg"?: string | number;
        /**
          * Medium column width
         */
        "md"?: string | number;
        /**
          * Small column width
         */
        "sm"?: string | number;
        /**
          * X-Large column width
         */
        "xl"?: string | number;
        /**
          * X-small column width
         */
        "xs"?: string | number;
    }
    interface SenContainer {
    }
    interface SenFormField {
        /**
          * Label of the form field
         */
        "label"?: string;
    }
    interface SenRow {
    }
    interface IntrinsicElements {
        "sen-app": SenApp;
        "sen-button": SenButton;
        "sen-button-group": SenButtonGroup;
        "sen-col": SenCol;
        "sen-container": SenContainer;
        "sen-form-field": SenFormField;
        "sen-row": SenRow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sen-app": LocalJSX.SenApp & JSXBase.HTMLAttributes<HTMLSenAppElement>;
            "sen-button": LocalJSX.SenButton & JSXBase.HTMLAttributes<HTMLSenButtonElement>;
            "sen-button-group": LocalJSX.SenButtonGroup & JSXBase.HTMLAttributes<HTMLSenButtonGroupElement>;
            "sen-col": LocalJSX.SenCol & JSXBase.HTMLAttributes<HTMLSenColElement>;
            "sen-container": LocalJSX.SenContainer & JSXBase.HTMLAttributes<HTMLSenContainerElement>;
            "sen-form-field": LocalJSX.SenFormField & JSXBase.HTMLAttributes<HTMLSenFormFieldElement>;
            "sen-row": LocalJSX.SenRow & JSXBase.HTMLAttributes<HTMLSenRowElement>;
        }
    }
}
